[package]
name = "axiom-sigblock-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.axiom-sigblock]
path = ".."

[[bin]]
name = "fuzz_locate"
path = "fuzz_targets/fuzz_locate.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_parse_v2"
path = "fuzz_targets/fuzz_parse_v2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_parse_v3"
path = "fuzz_targets/fuzz_parse_v3.rs"
test = false
doc = false
bench = false
