// Auto-generated by tools/lean-to-rust from
// theorems/Apkaxiom/Zip/LocalHeader.lean.
// Do not edit by hand — re-run `make extract`.
//
// Subset coverage: see tools/lean-to-rust/README.md
// (or the §D-1 ADR-0025 update).
#![forbid(unsafe_code)]
#![allow(clippy::too_many_arguments, clippy::doc_markdown, clippy::missing_errors_doc, missing_docs)]

// (skipped: import Std)

// (skipped: namespace Apkaxiom.Zip.LocalHeader)

/// Auto-extracted from Lean `def lfhSignature`.
pub fn lfh_signature() -> u32 {
    0x04034b50
}

/// Auto-extracted from Lean `def fixedSize`.
pub fn fixed_size() -> usize {
    30
}

/// Auto-extracted from Lean `def totalSize`.
pub fn total_size(name_len: u16, extra_len: u16) -> usize {
    ((FIXED_SIZE + name_len.to_nat) + extra_len.to_nat)
}

/// Lean structure `Lfh`. Auto-extracted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lfh {
    pub version_needed: u16,
    pub general_flags: u16,
    pub compression_method: u16,
    pub last_mod_time: u16,
    pub last_mod_date: u16,
    pub crc32: u32,
    pub compressed_size: u32,
    pub uncompressed_size: u32,
    pub file_name: Vec<u8>,
    pub extra_field: Vec<u8>,
}

/// Lean inductive `ParseError`. Auto-extracted.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParseError {
    ShortHeader,
    BadSignature,
    ShortName,
    ShortExtra,
}

// (skipped: instance @ line 74)

/// Auto-extracted from Lean `def ParseError.tag`.
impl ParseError {
    pub const fn tag(self) -> u8 {
        match self {
            ParseError::ShortHeader => 1,
            ParseError::BadSignature => 2,
            ParseError::ShortName => 3,
            ParseError::ShortExtra => 4,
        }
    }
}

// (skipped: theorem/example @ line 91)

/// Auto-extracted from Lean `def readU16`.
pub fn read_u16(bs: &[u8], o: usize) -> Option<u16> {
    if ((o + 1) < bs.size) { { let b0 = (bs[o]);
    { let b1 = (bs[((o + 1))]);
    some(((b0.to_u_int16 | ((b1.to_u_int16 << 8))))) } } } else { none }
}

/// Auto-extracted from Lean `def readU32`.
pub fn read_u32(bs: &[u8], o: usize) -> Option<u32> {
    if ((o + 3) < bs.size) { { let b0 = (bs[o]);
    { let b1 = (bs[((o + 1))]);
    { let b2 = (bs[((o + 2))]);
    { let b3 = (bs[((o + 3))]);
    some(((((b0.to_u_int32 | ((b1.to_u_int32 << 8))) | ((b2.to_u_int32 << 16))) | ((b3.to_u_int32 << 24))))) } } } } } else { none }
}

/// Auto-extracted from Lean `def slice`.
pub fn slice(bs: &[u8], o: usize, len: usize) -> Option<Vec<u8>> {
    if ((o + len) <= bs.size) { some((bs.extract(o, ((o + len))))) } else { none }
}

/// Auto-extracted from Lean `def parseLfh`.
pub fn parse_lfh(bs: &[u8]) -> Result<(Lfh, usize), ParseError> {
    if (bs.size < FIXED_SIZE) {
    return Err(ShortHeader);
    
    }
    let Some(sig) = read_u32(bs, 0) else { return Err(ShortHeader); };
    if (sig != LFH_SIGNATURE) {
    return Err(BadSignature);
    
    }
    let Some(version_needed) = read_u16(bs, 4) else { return Err(ShortHeader); };
    let Some(general_flags) = read_u16(bs, 6) else { return Err(ShortHeader); };
    let Some(compression_method) = read_u16(bs, 8) else { return Err(ShortHeader); };
    let Some(last_mod_time) = read_u16(bs, 10) else { return Err(ShortHeader); };
    let Some(last_mod_date) = read_u16(bs, 12) else { return Err(ShortHeader); };
    let Some(crc32) = read_u32(bs, 14) else { return Err(ShortHeader); };
    let Some(compressed_size) = read_u32(bs, 18) else { return Err(ShortHeader); };
    let Some(uncompressed_size) = read_u32(bs, 22) else { return Err(ShortHeader); };
    let Some(name_len) = read_u16(bs, 26) else { return Err(ShortHeader); };
    let Some(extra_len) = read_u16(bs, 28) else { return Err(ShortHeader); };
    let Some(file_name) = slice(bs, 30, name_len.to_nat) else { return Err(ShortName); };
    let Some(extra_field) = slice(bs, ((30 + name_len.to_nat)), extra_len.to_nat) else { return Err(ShortExtra); };
    let header = Lfh { version_needed: version_needed, general_flags: general_flags, compression_method: compression_method, last_mod_time: last_mod_time, last_mod_date: last_mod_date, crc32: crc32, compressed_size: compressed_size, uncompressed_size: uncompressed_size, file_name: file_name, extra_field: extra_field };
    return Ok((header, total_size(name_len, extra_len)));
}

/// Auto-extracted from Lean `def minimalLfhBytes`.
pub fn minimal_lfh_bytes() -> Vec<u8> {
    ByteArray.mk(vec![0x50, 0x4b, 0x03, 0x04, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00])
}

/// Auto-extracted from Lean `def parseError`.
pub fn parse_error(bs: &[u8]) -> Option<ParseError> {
    match parse_lfh(bs) {
        Err(e) => some(e),
        Ok(_) => none,
    }
}

// (skipped: theorem/example @ line 194)

// (skipped: theorem/example @ line 197)

// (skipped: theorem/example @ line 202)

// (skipped: end Apkaxiom.Zip.LocalHeader)

