# Copyright (c) APKAXIOM Authors. Apache-2.0 OR MIT.

rust_library(
    name = "axiom-l1-rs",
    srcs = glob(["src/**/*.rs"]),
    crate = "axiom_l1_rs",
    crate_root = "src/lib.rs",
    edition = "2021",
    deps = [
        "//crates/axiom-l0:axiom-l0",
        "//crates/axiom-zip-ref:axiom-zip-ref",
        "//third-party/rust:thiserror",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "axiom-l1-rs-test",
    srcs = glob(["src/**/*.rs"]),
    crate = "axiom_l1_rs",
    crate_root = "src/lib.rs",
    edition = "2021",
    deps = [
        "//crates/axiom-l0:axiom-l0",
        "//crates/axiom-zip-ref:axiom-zip-ref",
        "//third-party/rust:thiserror",
    ],
)
