// Copyright (c) APKAXIOM Authors. Apache-2.0 OR MIT.

//! P1.2 backwards-compatibility shim — the original toy
//! `Nat → Nat` extractor for `Apkaxiom.Hello`. Preserves the 3
//! unit tests the P1.2 sub-phase shipped with so the pedagogical
//! artefact still works under the P1.9 `lean-to-rust` binary.

#![allow(missing_docs)]

#[derive(Debug, thiserror::Error)]
pub enum P12Error {
    #[error("no extractable `def` found")]
    NoDef,
    #[error("unsupported expression: {0:?}")]
    Unsupported(String),
}

#[derive(Debug)]
struct Extracted {
    name: String,
    arg: String,
    body: String,
    test_cases: Vec<TestCase>,
}

#[derive(Debug)]
struct TestCase {
    name: String,
    arg_value: String,
    expected: String,
}

pub fn extract_render(src: &str) -> Result<String, P12Error> {
    let ext = parse(src)?;
    render(&ext)
}

fn parse(src: &str) -> Result<Extracted, P12Error> {
    let mut pending: Vec<TestCase> = Vec::new();
    for line in src.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("--!") {
            if let Some(tc) = parse_test_directive(rest.trim()) {
                pending.push(tc);
            }
            continue;
        }
        if !trimmed.starts_with("def ") {
            continue;
        }
        let after_def = trimmed.strip_prefix("def ").unwrap_or(trimmed);
        let (name, rest) = split_first_token(after_def);
        let rest = rest.trim_start();
        let (arg, after) = if let Some(rest) = rest.strip_prefix('(') {
            let close = rest.find(')').ok_or(P12Error::Unsupported(line.into()))?;
            let inside = &rest[..close];
            let after = rest[close + 1..].trim_start();
            let arg_name = inside.split(':').next().unwrap_or("").trim();
            (arg_name.to_string(), after)
        } else {
            (String::new(), rest)
        };
        let after_colon_nat = after
            .trim_start_matches(':')
            .trim_start()
            .strip_prefix("Nat")
            .ok_or(P12Error::Unsupported(line.into()))?;
        let body = after_colon_nat
            .trim_start()
            .strip_prefix(":=")
            .ok_or(P12Error::Unsupported(line.into()))?
            .trim()
            .to_string();
        return Ok(Extracted {
            name,
            arg,
            body,
            test_cases: std::mem::take(&mut pending),
        });
    }
    Err(P12Error::NoDef)
}

fn parse_test_directive(rest: &str) -> Option<TestCase> {
    let rest = rest.strip_prefix("test ")?.trim();
    let paren = rest.find('(')?;
    let close = rest.find(')')?;
    let eq = rest.find('=')?;
    if !(paren < close && close < eq) {
        return None;
    }
    Some(TestCase {
        name: rest[..paren].trim().to_string(),
        arg_value: rest[paren + 1..close].trim().to_string(),
        expected: rest[eq + 1..].trim().to_string(),
    })
}

fn split_first_token(s: &str) -> (String, &str) {
    let mut end = 0usize;
    for (i, c) in s.char_indices() {
        if c.is_whitespace() || c == '(' || c == ':' {
            end = i;
            break;
        }
        end = i + c.len_utf8();
    }
    (s[..end].to_string(), &s[end..])
}

fn render(ext: &Extracted) -> Result<String, P12Error> {
    let allowed = |c: char| {
        c.is_ascii_alphanumeric()
            || matches!(
                c,
                '+' | '-' | '*' | '/' | '%' | '(' | ')' | ' ' | '_' | '\t'
            )
    };
    if !ext.body.chars().all(allowed) {
        return Err(P12Error::Unsupported(ext.body.clone()));
    }
    let body_rust = &ext.body;
    let fn_sig = if ext.arg.is_empty() {
        format!(
            "pub const fn {}() -> u64 {{\n    {}\n}}",
            ext.name, body_rust
        )
    } else {
        let name = &ext.name;
        let arg = &ext.arg;
        format!("pub const fn {name}({arg}: u64) -> u64 {{\n    {body_rust}\n}}")
    };
    let trailing_newline = ext.test_cases.is_empty();
    let tests = if ext.test_cases.is_empty() {
        String::new()
    } else {
        let cases = ext
            .test_cases
            .iter()
            .map(|tc| {
                let test_name = &tc.name;
                let fn_name = &ext.name;
                let input = &tc.arg_value;
                let expected = &tc.expected;
                format!(
                    "    #[test]\n    fn {test_name}() {{\n        assert_eq!({fn_name}({input}), {expected});\n    }}"
                )
            })
            .collect::<Vec<_>>()
            .join("\n");
        format!("\n\n#[cfg(test)]\nmod tests {{\n    use super::*;\n{cases}\n}}\n")
    };
    let trailing = if trailing_newline { "\n" } else { "" };
    Ok(format!(
        "// Auto-generated by tools/lean-to-rust (P1.2 toy path).\n#![forbid(unsafe_code)]\n\n#[must_use]\n{fn_sig}{tests}{trailing}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_double() {
        let src = "\
            --! test double_zero(0) = 0\n\
            --! test double_seven(7) = 14\n\
            def double (n : Nat) : Nat := 2 * n\n\
        ";
        let out = extract_render(src).unwrap();
        assert!(out.contains("pub const fn double(n: u64) -> u64"));
        assert!(out.contains("assert_eq!(double(0), 0);"));
    }

    #[test]
    fn rejects_unsupported_expr() {
        let bad = "def g (n : Nat) : Nat := \"hello\"\n";
        assert!(matches!(extract_render(bad), Err(P12Error::Unsupported(_))));
    }

    #[test]
    fn nullary_def() {
        let src = "def answer : Nat := 42\n";
        let out = extract_render(src).unwrap();
        assert!(out.contains("pub const fn answer() -> u64"));
    }
}
