// Copyright (c) APKAXIOM Authors. Apache-2.0 OR MIT.

//! P1.9 Lean→Rust translator/emitter.
//!
//! Lowers the [`crate::ast`] of the verified-parser subset into a
//! single Rust source file. The output is intentionally
//! human-readable (we want code review, not magic): identifiers
//! are renamed Lean→Rust style (camelCase fields → snake_case),
//! `Except` becomes `Result`, `Option` stays `Option`, `ByteArray`
//! becomes `&[u8]` for parameters and `Vec<u8>` for owning fields,
//! `Id.run do` becomes a straight-line Rust function body.
//!
//! Anything we can't lower deterministically is rejected loudly.

#![allow(missing_docs, clippy::too_long_first_doc_paragraph)]

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::ast::*;

#[derive(Debug, thiserror::Error)]
pub enum TranslateError {
    #[error("translate error: {0}")]
    Generic(String),
}

/// Carry environment across a translation pass — names of declared
/// structs/inductives, parameter modes, etc. Lets us pick the right
/// Rust shape for `ByteArray` (borrowed in params, owned in fields).
#[derive(Debug, Default)]
pub struct Env {
    /// Set of inductive names (for `.ctor` resolution).
    pub inductives: BTreeMap<String, Vec<String>>,
    /// Set of structure names (for `{ … }` resolution).
    pub structs: BTreeMap<String, Vec<String>>,
    /// Map ident-aliases — Lean's `a` may need to become Rust's `a_`
    /// if it shadows a keyword.
    pub aliases: BTreeMap<String, String>,
}

impl Env {
    pub fn from_module(m: &Module) -> Self {
        let mut env = Env::default();
        for item in &m.items {
            match item {
                Item::Inductive(i) => {
                    env.inductives.insert(
                        i.name.clone(),
                        i.ctors.iter().map(|c| c.name.clone()).collect(),
                    );
                }
                Item::Struct(s) => {
                    env.structs.insert(
                        s.name.clone(),
                        s.fields.iter().map(|f| f.name.clone()).collect(),
                    );
                }
                _ => {}
            }
        }
        env
    }
}

pub fn emit_module(m: &Module, env: &Env) -> Result<String, TranslateError> {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by tools/lean-to-rust from").unwrap();
    writeln!(out, "// theorems/Apkaxiom/Zip/LocalHeader.lean.").unwrap();
    writeln!(out, "// Do not edit by hand — re-run `make extract`.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// Subset coverage: see tools/lean-to-rust/README.md").unwrap();
    writeln!(out, "// (or the §D-1 ADR-0025 update).").unwrap();
    writeln!(out, "#![forbid(unsafe_code)]").unwrap();
    writeln!(
        out,
        "#![allow(clippy::too_many_arguments, clippy::doc_markdown, clippy::missing_errors_doc, missing_docs, unused_parens, clippy::unnecessary_wraps, clippy::missing_const_for_fn, clippy::redundant_field_names, clippy::unreadable_literal, clippy::double_parens, clippy::needless_return, clippy::manual_let_else, clippy::use_self)]"
    )
    .unwrap();
    writeln!(out).unwrap();

    for item in &m.items {
        match item {
            Item::Def(d) => emit_def(&mut out, d, env)?,
            Item::Struct(s) => emit_struct(&mut out, s)?,
            Item::Inductive(i) => emit_inductive(&mut out, i)?,
            Item::Namespace(_)
            | Item::EndNamespace(_)
            | Item::ImportSkipped(_)
            | Item::InstanceSkipped { .. }
            | Item::TheoremSkipped { .. } => {
                // Skipped top-level constructs — preserved as
                // comments so the output documents what was elided.
                writeln!(out, "// (skipped: {})", describe_item(item)).unwrap();
                writeln!(out).unwrap();
            }
        }
    }
    Ok(out)
}

fn describe_item(item: &Item) -> String {
    match item {
        Item::Namespace(n) => format!("namespace {n}"),
        Item::EndNamespace(n) => format!("end {n}"),
        Item::ImportSkipped(n) => format!("import {n}"),
        Item::InstanceSkipped { line } => format!("instance @ line {line}"),
        Item::TheoremSkipped { line } => format!("theorem/example @ line {line}"),
        _ => "?".into(),
    }
}

fn emit_struct(out: &mut String, s: &StructItem) -> Result<(), TranslateError> {
    writeln!(out, "/// Lean structure `{}`. Auto-extracted.", s.name).unwrap();
    let mut derives = vec![
        "Debug".to_string(),
        "Clone".to_string(),
        "PartialEq".to_string(),
        "Eq".to_string(),
    ];
    for d in &s.derives {
        if d == "Inhabited" {
            // Rust's equivalent is Default; not always derivable.
            // Skip — adding it would break for ByteArray fields
            // that don't have Default.
        }
    }
    derives.dedup();
    writeln!(out, "#[derive({})]", derives.join(", ")).unwrap();
    writeln!(out, "pub struct {} {{", s.name).unwrap();
    for f in &s.fields {
        let rust_ty = render_type(&f.ty, TypePosition::OwnedField);
        let rust_name = lean_to_rust_field(&f.name);
        writeln!(out, "    pub {rust_name}: {rust_ty},").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

fn emit_inductive(out: &mut String, i: &InductiveItem) -> Result<(), TranslateError> {
    writeln!(out, "/// Lean inductive `{}`. Auto-extracted.", i.name).unwrap();
    writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub enum {} {{", i.name).unwrap();
    for c in &i.ctors {
        if c.args.is_empty() {
            writeln!(out, "    {},", capitalize(&c.name)).unwrap();
        } else {
            return Err(TranslateError::Generic(format!(
                "non-nullary constructor `{}` not yet supported",
                c.name
            )));
        }
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

fn emit_def(out: &mut String, d: &DefItem, env: &Env) -> Result<(), TranslateError> {
    // Special-cased: `ParseError.tag` returns `UInt8` from a Lean
    // pattern match expressed as a function-with-no-explicit-args.
    // Lean's surface uses `ParseError → UInt8` syntax — our parser
    // emits a `Named` type encoding for this (see parser.rs).
    if let Type::Named(s) = &d.return_ty {
        if s.contains("->") {
            return emit_enum_method(out, d);
        }
    }

    // Nullary def over a primitive numeric / bool with a literal
    // body → emit as a Rust `const`. References to it then resolve
    // as constants too (uppercase via `render_ident`).
    if d.params.is_empty() && is_primitive_numeric(&d.return_ty) && is_const_literal_body(&d.body) {
        let const_name = render_ident(&d.name);
        let ty = render_type(&d.return_ty, TypePosition::Return);
        let body = render_expr(&d.body, env, 0)?;
        writeln!(out, "/// Auto-extracted from Lean `def {}`.", d.name).unwrap();
        writeln!(out, "pub const {const_name}: {ty} = {body};").unwrap();
        writeln!(out).unwrap();
        return Ok(());
    }

    // Plain `def` — translate to `pub fn`.
    let return_ty = render_type(&d.return_ty, TypePosition::Return);
    let params: Vec<String> = d
        .params
        .iter()
        .map(|p| {
            format!(
                "{}: {}",
                lean_to_rust_field(&p.name),
                render_type(&p.ty, TypePosition::Param)
            )
        })
        .collect();
    writeln!(out, "/// Auto-extracted from Lean `def {}`.", d.name).unwrap();
    let const_qualifier = if is_const_eligible(&d.body) {
        "const "
    } else {
        ""
    };
    writeln!(
        out,
        "pub {const_qualifier}fn {}({}) -> {return_ty} {{",
        lean_to_rust_field(&d.name),
        params.join(", ")
    )
    .unwrap();
    let body = render_expr(&d.body, env, 1)?;
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

/// Specialised emission for `def Type.method : Type → Result`
/// pattern — Lean's `ParseError.tag : ParseError → UInt8`. The body
/// is always a `match` over the inductive's constructors.
fn emit_enum_method(out: &mut String, d: &DefItem) -> Result<(), TranslateError> {
    // Split `EnumName.method` from the def name.
    let (enum_name, method) = d
        .name
        .rsplit_once('.')
        .ok_or_else(|| TranslateError::Generic(format!("`{}` is not Type.method", d.name)))?;
    let return_ty = match &d.return_ty {
        Type::Named(s) if s.contains("->") => {
            // The pseudo-type encodes "Domain -> Codomain".
            let parts: Vec<&str> = s.splitn(2, " -> ").collect();
            // `parts[1]` is something like `UInt(8)` (Debug repr) or a Named.
            // Map back via a small heuristic.
            // Easier: look at the body to infer Rust return — but
            // here we know LocalHeader.lean uses UInt8.
            if parts[1].contains("UInt(8)") {
                "u8"
            } else if parts[1].contains("UInt(16)") {
                "u16"
            } else if parts[1].contains("UInt(32)") {
                "u32"
            } else if parts[1].contains("UInt(64)") {
                "u64"
            } else {
                return Err(TranslateError::Generic(format!(
                    "unsupported codomain `{}` for enum method",
                    parts[1]
                )));
            }
        }
        _ => unreachable!(),
    };
    let method_snake = lean_to_rust_field(method);
    writeln!(out, "/// Auto-extracted from Lean `def {}`.", d.name).unwrap();
    writeln!(out, "impl {enum_name} {{").unwrap();
    writeln!(
        out,
        "    pub const fn {method_snake}(self) -> {return_ty} {{"
    )
    .unwrap();
    // Body: `match self { ... }`.
    let body = match &d.body {
        Expr::Match { scrutinee: _, arms } => {
            let mut s = String::new();
            writeln!(s, "match self {{").unwrap();
            for arm in arms {
                let p = render_pattern(&arm.pat, enum_name);
                let v = render_expr(&arm.body, &Env::default(), 0)?;
                writeln!(s, "    {p} => {v},").unwrap();
            }
            writeln!(s, "}}").unwrap();
            s
        }
        _ => {
            return Err(TranslateError::Generic(
                "enum-method body must be a `match`".into(),
            ));
        }
    };
    for line in body.lines() {
        writeln!(out, "        {line}").unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

#[derive(Debug, Clone, Copy)]
enum TypePosition {
    /// Function parameter — borrow ByteArrays as `&[u8]`.
    Param,
    /// Return type — owned `Vec<u8>` for ByteArrays.
    Return,
    /// Owning struct field — owned `Vec<u8>`.
    OwnedField,
}

fn render_type(t: &Type, pos: TypePosition) -> String {
    match t {
        Type::UInt(8) => "u8".into(),
        Type::UInt(16) => "u16".into(),
        Type::UInt(32) => "u32".into(),
        Type::UInt(64) => "u64".into(),
        Type::UInt(_) => "u64".into(),
        Type::Nat => "usize".into(),
        Type::Bool => "bool".into(),
        Type::String_ => "String".into(),
        Type::ByteArray => match pos {
            TypePosition::Param => "&[u8]".into(),
            _ => "Vec<u8>".into(),
        },
        Type::Option(inner) => format!("Option<{}>", render_type(inner, pos)),
        Type::Except(err, ok) => format!(
            "Result<{}, {}>",
            render_type(ok, pos),
            render_type(err, pos)
        ),
        Type::Prod(a, b) => format!("({}, {})", render_type(a, pos), render_type(b, pos)),
        Type::Named(s) => s.clone(),
    }
}

fn lean_to_rust_field(name: &str) -> String {
    // Rust keywords we need to escape.
    if matches!(
        name,
        "type"
            | "fn"
            | "match"
            | "if"
            | "else"
            | "let"
            | "loop"
            | "return"
            | "ref"
            | "use"
            | "mod"
            | "self"
            | "super"
            | "crate"
            | "Self"
    ) {
        return format!("{name}_");
    }
    // CamelCase → snake_case for field-like positions. Type names
    // (CamelCase) stay as-is.
    let chars: Vec<char> = name.chars().collect();
    if chars.is_empty() {
        return String::new();
    }
    if chars[0].is_ascii_uppercase() {
        return name.to_string();
    }
    // Lower-camelCase → snake_case with acronym preservation:
    //   readU16          → read_u16
    //   uncompressedSize → uncompressed_size
    //   toUInt16         → to_uint16   (NOT to_u_int16)
    //   parseLfh         → parse_lfh
    //   crc32            → crc32
    //
    // Algorithm: walk left-to-right; on each uppercase boundary
    // emit '_'. Within a run of uppercase letters/digits, treat
    // them as one logical "word" — but if the run is followed by a
    // lowercase letter, the last uppercase letter starts the next
    // word (e.g., `XMLParser` → `xml_parser`).
    let mut out = String::with_capacity(name.len() + 4);
    let mut i = 0usize;
    while i < chars.len() {
        let c = chars[i];
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            let mut j = i;
            while j < chars.len() && (chars[j].is_ascii_uppercase() || chars[j].is_ascii_digit()) {
                j += 1;
            }
            let run_end = if j - i > 1 && j < chars.len() && chars[j].is_ascii_lowercase() {
                j - 1
            } else {
                j
            };
            for &uc in &chars[i..run_end] {
                out.push(uc.to_ascii_lowercase());
            }
            i = run_end;
        } else {
            out.push(c);
            i += 1;
        }
    }
    out
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn render_pattern(p: &Pattern, enum_name: &str) -> String {
    match p {
        Pattern::Wildcard => "_".into(),
        Pattern::Ident(s) => s.clone(),
        Pattern::Ctor { name, args } => {
            let cap = capitalize(name);
            if args.is_empty() {
                format!("{enum_name}::{cap}")
            } else {
                let inner: Vec<String> =
                    args.iter().map(|a| render_pattern(a, enum_name)).collect();
                format!("{enum_name}::{cap}({})", inner.join(", "))
            }
        }
    }
}

fn is_const_eligible(_: &Expr) -> bool {
    // Heuristic: avoid emitting `const fn` since most of our subset
    // calls non-const helpers (`.get!`, `.extract`). We'd need
    // const-trait propagation to be sure, so opt out for now.
    false
}

/// `true` if the type is a primitive numeric (UIntN, Nat) — these
/// are the cases where Lean's `def name : T := lit` is meant as a
/// named constant rather than a thunk.
fn is_primitive_numeric(t: &Type) -> bool {
    matches!(t, Type::UInt(_) | Type::Nat | Type::Bool)
}

/// `true` if the expression is a literal we can put on the RHS of
/// `pub const NAME: T = …;`. The Lean source uses `0x04034b50`
/// (IntLit), `30` (IntLit), `true`/`false` (BoolLit). We allow
/// parenthesised literals for safety.
fn is_const_literal_body(e: &Expr) -> bool {
    match e {
        Expr::IntLit(_) | Expr::BoolLit(_) | Expr::StrLit(_) => true,
        Expr::Paren(inner) => is_const_literal_body(inner),
        Expr::Neg(inner) => matches!(inner.as_ref(), Expr::IntLit(_) | Expr::Paren(_)),
        _ => false,
    }
}

fn render_expr(e: &Expr, env: &Env, depth: usize) -> Result<String, TranslateError> {
    Ok(match e {
        Expr::IntLit(s) => s.clone(),
        Expr::BoolLit(true) => "true".into(),
        Expr::BoolLit(false) => "false".into(),
        Expr::StrLit(s) => format!("\"{s}\""),
        Expr::Ident(s) => render_ident(s),
        Expr::DotCtor { ctor } => render_dot_ctor_envful(ctor, env),
        Expr::App { head, arg } => render_app(head, arg, env, depth)?,
        Expr::BinOp { op, lhs, rhs } => {
            let op_str = render_binop(*op);
            format!(
                "({} {op_str} {})",
                render_expr(lhs, env, depth)?,
                render_expr(rhs, env, depth)?
            )
        }
        Expr::Neg(e) => format!("-({})", render_expr(e, env, depth)?),
        Expr::Not(e) => format!("!({})", render_expr(e, env, depth)?),
        Expr::If { cond, then_, else_ } => {
            format!(
                "if {} {{ {} }} else {{ {} }}",
                render_expr(cond, env, depth)?,
                render_expr(then_, env, depth)?,
                render_expr(else_, env, depth)?
            )
        }
        Expr::Let {
            binder,
            ty,
            value,
            bail,
            body,
        } => render_let(
            binder,
            ty.as_ref(),
            value,
            bail.as_deref(),
            body,
            env,
            depth,
        )?,
        Expr::Match { scrutinee, arms } => {
            // Without env-side enum context we can't always know the
            // enum name; fall back to printing `match … { … }`.
            let scr = render_expr(scrutinee, env, depth)?;
            let mut s = format!("match {scr} {{\n");
            for arm in arms {
                let p = render_pattern_envful(&arm.pat, env);
                let b = render_expr(&arm.body, env, depth + 1)?;
                writeln!(s, "    {p} => {b},").unwrap();
            }
            s.push('}');
            s
        }
        Expr::IdRunDo { stmts } => render_id_run_do(stmts, env, depth)?,
        Expr::Return(e) => format!("return {};", render_expr(e, env, depth)?),
        Expr::StructLit { type_hint, fields } => {
            render_struct_lit(type_hint.as_deref(), fields, env, depth)?
        }
        Expr::Paren(inner) => format!("({})", render_expr(inner, env, depth)?),
        Expr::Tuple(elts) => {
            let parts: Vec<String> = elts
                .iter()
                .map(|e| render_expr(e, env, depth))
                .collect::<Result<_, _>>()?;
            format!("({})", parts.join(", "))
        }
        Expr::ArrayLit(elts) => {
            let parts: Vec<String> = elts
                .iter()
                .map(|e| render_expr(e, env, depth))
                .collect::<Result<_, _>>()?;
            // Most likely a byte array → emit as `vec![ … ]`.
            format!("vec![{}]", parts.join(", "))
        }
    })
}

fn render_ident(s: &str) -> String {
    // Special idents that map to Rust counterparts.
    match s {
        "lfhSignature" => return "LFH_SIGNATURE".into(),
        "fixedSize" => return "FIXED_SIZE".into(),
        "totalSize" => return "total_size".into(),
        "readU16" => return "read_u16".into(),
        "readU32" => return "read_u32".into(),
        "slice" => return "slice".into(),
        "parseLfh" => return "parse_lfh".into(),
        "minimalLfhBytes" => return "minimal_lfh_bytes".into(),
        "parseError" => return "parse_error".into(),
        // Plain Lean ctor identifiers that map to Rust prelude.
        "some" => return "Some".into(),
        "none" => return "None".into(),
        "ok" => return "Ok".into(),
        "error" => return "Err".into(),
        _ => {}
    }
    // Dotted identifier: `bs.size`, `b0.toUInt16`, `nameLen.toNat`.
    // These are method-style accesses Lean's name-resolver expands;
    // we lower them to Rust method calls / field accesses.
    if let Some((recv, method)) = s.rsplit_once('.') {
        // Capitalised receiver = type-namespace path
        // (`ByteArray.mk`, `ParseError.tag` already handled
        // upstream). Lower dotted-ident as a zero-arg method call
        // when the receiver is a value (lowercase initial).
        let first = recv.chars().next().unwrap_or(' ');
        if first.is_ascii_lowercase() || first == '_' {
            // Use the same dispatch table as method calls, but
            // with no arguments. Reuse `render_method_call` via a
            // synthesised empty-arg call.
            return render_method_call_zero_arg(recv, method);
        }
        // Capitalised receiver — qualified path / namespaced
        // function name. Snake-case the method.
        return format!("{}::{}", recv, lean_to_rust_field(method));
    }
    lean_to_rust_field(s)
}

/// Zero-arg form of [`render_method_call`] for the dotted-ident
/// case. Mirrors the dispatch table; kept separate because the
/// signature is simpler (no env / depth).
fn render_method_call_zero_arg(recv: &str, method: &str) -> String {
    let recv_rust = lean_to_rust_field(recv);
    match method {
        "size" => format!("{recv_rust}.len()"),
        "toUInt8" => format!("u8::from({recv_rust})"),
        "toUInt16" => format!("u16::from({recv_rust})"),
        "toUInt32" => format!("u32::from({recv_rust})"),
        "toUInt64" => format!("u64::from({recv_rust})"),
        "toNat" => format!("({recv_rust} as usize)"),
        // Generic field access.
        _ => format!("{recv_rust}.{}", lean_to_rust_field(method)),
    }
}

fn render_dot_ctor_envful(ctor: &str, env: &Env) -> String {
    // Standard Option/Result projectors.
    match ctor {
        "some" => return "Some".into(),
        "none" => return "None".into(),
        "error" => return "Err".into(),
        "ok" => return "Ok".into(),
        _ => {}
    }
    // Try to resolve against a known inductive: if exactly one
    // declared inductive has this constructor name, prefix with
    // the enum name. Multiple matches → ambiguous (shouldn't
    // happen in our subset); fall back to bare capitalised name.
    let mut matches: Vec<&String> = env
        .inductives
        .iter()
        .filter_map(|(enum_name, ctors)| {
            if ctors.iter().any(|c| c == ctor) {
                Some(enum_name)
            } else {
                None
            }
        })
        .collect();
    matches.sort();
    if matches.len() == 1 {
        return format!("{}::{}", matches[0], capitalize(ctor));
    }
    capitalize(ctor)
}

fn render_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NEq => "!=",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}

fn render_app(head: &Expr, arg: &Expr, env: &Env, depth: usize) -> Result<String, TranslateError> {
    // Lean idioms we handle specially:
    //   - `bs.get! o`            → bs[o]              (after copy)
    //   - `bs.size`              → bs.len()           (zero-arg method)
    //   - `bs.extract a b`       → bs[a..b].to_vec()  (slice-to-Vec)
    //   - `b0.toUInt16`          → u16::from(b0)
    //   - `b0.toUInt32`          → u32::from(b0)
    //   - `nameLen.toNat`        → name_len as usize
    //   - `ByteArray.mk arr`     → arr                (mk is identity)
    //   - `.error e`             → Err(e)
    //   - `.ok v`                → Ok(v)
    //   - `.some x`              → Some(x)
    //   - `.error .shortHeader`  → Err(ParseError::ShortHeader)
    //   - generic `f x y z`      → f(x, y, z)

    // Collect the full chain before deciding how to render. The
    // bottom of the App chain is the callee; everything else is an
    // argument list in source order.
    let (callee, args) = collect_app(head, arg);

    // Method-style call: callee is `Ident("recv.method")`.
    // Only treat as a method if the receiver is a value (lowercase
    // start) — otherwise it's a qualified path like `ByteArray.mk`.
    if let Expr::Ident(s) = callee {
        if let Some((recv, method)) = s.rsplit_once('.') {
            // `ByteArray.mk` — capitalised receiver; route through
            // the method dispatcher so `mk` becomes identity.
            // `bs.extract` / `b0.toUInt16` — lowercase receiver;
            // method dispatch.
            return render_method_call(recv, method, &args, env, depth);
        }
    }

    let mut arg_strs: Vec<String> = Vec::with_capacity(args.len());
    for a in args {
        arg_strs.push(render_expr(a, env, depth)?);
    }

    // `.error e` / `.ok v` / `.some x` — anonymous projector with
    // an argument. Emit Result/Option ctor.
    //
    // Note: arg_strs already routes through `render_dot_ctor_envful`,
    // so bare `.shortHeader` arguments are pre-qualified to
    // `ParseError::ShortHeader`. That makes `.error .shortHeader`
    // round-trip into `Err(ParseError::ShortHeader)` correctly.
    if let Expr::DotCtor { ctor } = callee {
        let mapped = match ctor.as_str() {
            "some" => "Some",
            "none" => "None", // shouldn't take args but handled defensively
            "error" => "Err",
            "ok" => "Ok",
            other => {
                // Inductive ctor with args. Qualify via env if
                // possible.
                let qualified = render_dot_ctor_envful(other, env);
                return Ok(format!("{qualified}({})", arg_strs.join(", ")));
            }
        };
        return Ok(format!("{mapped}({})", arg_strs.join(", ")));
    }

    let callee_str = render_expr(callee, env, depth)?;
    Ok(format!("{callee_str}({})", arg_strs.join(", ")))
}

fn collect_app<'a>(head: &'a Expr, arg: &'a Expr) -> (&'a Expr, Vec<&'a Expr>) {
    let mut args = vec![arg];
    let mut h = head;
    while let Expr::App {
        head: inner_h,
        arg: inner_a,
    } = h
    {
        args.push(inner_a);
        h = inner_h;
    }
    args.reverse();
    (h, args)
}

/// Render a Lean method-style call `recv.method args*`.
///
/// The receiver `recv` is the Lean source name; we lower it to its
/// Rust counterpart via `render_ident` so namespaced types (like
/// `ByteArray`, `UInt32`) get recognised. The `method` name drives
/// the dispatch — most idioms are translated structurally.
fn render_method_call(
    recv: &str,
    method: &str,
    args: &[&Expr],
    env: &Env,
    depth: usize,
) -> Result<String, TranslateError> {
    let recv_rust = render_ident(recv);
    let mut arg_strs = Vec::with_capacity(args.len());
    for a in args {
        arg_strs.push(render_expr(a, env, depth)?);
    }

    match (recv, method) {
        // `ByteArray.mk arr` → `arr` (the constructor is the
        // identity for our `&[u8]` lowering).
        ("ByteArray", "mk") if arg_strs.len() == 1 => Ok(arg_strs.into_iter().next().unwrap()),
        // Numeric type-cast methods. Lean spells these as
        // `b0.toUInt16`; in Rust we want `u16::from(b0)`.
        (_, "toUInt8") if arg_strs.is_empty() => Ok(format!("u8::from({recv_rust})")),
        (_, "toUInt16") if arg_strs.is_empty() => Ok(format!("u16::from({recv_rust})")),
        (_, "toUInt32") if arg_strs.is_empty() => Ok(format!("u32::from({recv_rust})")),
        (_, "toUInt64") if arg_strs.is_empty() => Ok(format!("u64::from({recv_rust})")),
        // `.toNat` lowers to `as usize`. UInt8/16 don't directly
        // implement `From<usize>`, so we use `as`.
        (_, "toNat") if arg_strs.is_empty() => Ok(format!("({recv_rust} as usize)")),
        // ByteArray accessors.
        (_, "size") if arg_strs.is_empty() => Ok(format!("{recv_rust}.len()")),
        (_, "get!") if arg_strs.len() == 1 => Ok(format!("{recv_rust}[{}]", arg_strs[0])),
        (_, "extract") if arg_strs.len() == 2 => Ok(format!(
            "{recv_rust}[{}..{}].to_vec()",
            arg_strs[0], arg_strs[1]
        )),
        // Generic method call — e.g. `Function.Injective` would land
        // here, but we don't actually use it at runtime. Lower as a
        // best-effort method call so the emitter doesn't choke; the
        // output won't necessarily compile but it's a clear signal
        // the translator needs an extension.
        _ => {
            let m = lean_to_rust_field(method);
            if arg_strs.is_empty() {
                Ok(format!("{recv_rust}.{m}"))
            } else {
                Ok(format!("{recv_rust}.{m}({})", arg_strs.join(", ")))
            }
        }
    }
}

fn render_pattern_envful(p: &Pattern, env: &Env) -> String {
    match p {
        Pattern::Wildcard => "_".into(),
        Pattern::Ident(s) => s.clone(),
        Pattern::Ctor { name, args } => {
            let cap = capitalize(name);
            // Try to find which inductive owns this ctor.
            for (enum_name, ctors) in &env.inductives {
                if ctors.iter().any(|c| c == name) {
                    if args.is_empty() {
                        return format!("{enum_name}::{cap}");
                    }
                }
            }
            // Not in our inductives — treat as `Some`/`None`/`Ok`/`Err`.
            match name.as_str() {
                "some" => format!("Some({})", join_pats_envful(args, env)),
                "none" => "None".into(),
                "ok" => format!("Ok({})", join_pats_envful(args, env)),
                "error" => format!("Err({})", join_pats_envful(args, env)),
                _ => format!("{cap}({})", join_pats_envful(args, env)),
            }
        }
    }
}

fn join_pats_envful(pats: &[Pattern], env: &Env) -> String {
    pats.iter()
        .map(|p| render_pattern_envful(p, env))
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_let(
    binder: &LetBinder,
    _ty: Option<&Type>,
    value: &Expr,
    bail: Option<&Expr>,
    body: &Expr,
    env: &Env,
    depth: usize,
) -> Result<String, TranslateError> {
    let value_str = render_expr(value, env, depth)?;
    let body_str = render_expr(body, env, depth)?;
    match binder {
        LetBinder::Ident(name) => {
            let n = lean_to_rust_field(name);
            Ok(format!("{{ let {n} = {value_str};\n{body_str} }}"))
        }
        LetBinder::SomePat(name) => {
            // `let .some x := v | bail` -> `let Some(x) = v else { bail }`.
            let n = lean_to_rust_field(name);
            let bail_str = match bail {
                Some(b) => render_expr(b, env, depth)?,
                None => {
                    return Err(TranslateError::Generic(
                        "let .some without `| bail` not supported".into(),
                    ))
                }
            };
            Ok(format!(
                "{{ let Some({n}) = {value_str} else {{ {bail_str} }};\n{body_str} }}"
            ))
        }
    }
}

fn render_id_run_do(stmts: &[DoStmt], env: &Env, depth: usize) -> Result<String, TranslateError> {
    let mut out = String::new();
    for s in stmts {
        match s {
            DoStmt::Let {
                binder,
                ty: _,
                value,
                bail,
            } => {
                let v = render_expr(value, env, depth)?;
                match binder {
                    LetBinder::Ident(n) => {
                        let n = lean_to_rust_field(n);
                        writeln!(out, "let {n} = {v};").unwrap();
                    }
                    LetBinder::SomePat(name) => {
                        let n = lean_to_rust_field(name);
                        let b = match bail {
                            Some(b) => render_expr(b, env, depth)?,
                            None => {
                                return Err(TranslateError::Generic(
                                    "do-block let .some without `| bail` not supported".into(),
                                ))
                            }
                        };
                        writeln!(out, "let Some({n}) = {v} else {{ {b} }};").unwrap();
                    }
                }
            }
            DoStmt::If { cond, then_, else_ } => {
                let c = render_expr(cond, env, depth)?;
                let t = render_do_stmts(then_, env, depth + 1)?;
                if let Some(e) = else_ {
                    let eb = render_do_stmts(e, env, depth + 1)?;
                    writeln!(out, "if {c} {{\n{t}\n}} else {{\n{eb}\n}}").unwrap();
                } else {
                    writeln!(out, "if {c} {{\n{t}\n}}").unwrap();
                }
            }
            DoStmt::Return(e) => {
                let v = render_expr(e, env, depth)?;
                writeln!(out, "return {v};").unwrap();
            }
            DoStmt::Tail(e) => {
                let v = render_expr(e, env, depth)?;
                writeln!(out, "{v}").unwrap();
            }
        }
    }
    Ok(out)
}

fn render_do_stmts(stmts: &[DoStmt], env: &Env, depth: usize) -> Result<String, TranslateError> {
    render_id_run_do(stmts, env, depth)
}

fn render_struct_lit(
    type_hint: Option<&str>,
    fields: &[StructLitField],
    env: &Env,
    depth: usize,
) -> Result<String, TranslateError> {
    // Resolve struct name. If type_hint isn't set we look at the
    // fields and try to match against env.structs.
    let struct_name: String = if let Some(h) = type_hint {
        h.to_string()
    } else {
        let field_names: Vec<&str> = fields.iter().map(|f| f.name.as_str()).collect();
        let mut found = None;
        for (name, declared) in &env.structs {
            if field_names.iter().all(|f| declared.iter().any(|d| d == *f)) {
                found = Some(name.clone());
                break;
            }
        }
        found.ok_or_else(|| {
            TranslateError::Generic(format!(
                "couldn't infer struct type for `{{ {field_names:?} }}`"
            ))
        })?
    };
    let mut out = format!("{struct_name} {{ ");
    let mut first = true;
    for f in fields {
        if !first {
            out.push_str(", ");
        }
        first = false;
        let n = lean_to_rust_field(&f.name);
        match &f.value {
            Some(v) => {
                let v_str = render_expr(v, env, depth)?;
                out.push_str(&format!("{n}: {v_str}"));
            }
            None => {
                // Lean punning: { field } means { field: field }.
                out.push_str(&format!("{n}: {n}"));
            }
        }
    }
    out.push_str(" }");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lean_to_rust_field_camel() {
        assert_eq!(lean_to_rust_field("readU16"), "read_u16");
        assert_eq!(lean_to_rust_field("uncompressedSize"), "uncompressed_size");
        assert_eq!(lean_to_rust_field("Lfh"), "Lfh");
    }

    #[test]
    fn render_simple_type() {
        assert_eq!(render_type(&Type::UInt(16), TypePosition::Param), "u16");
        assert_eq!(render_type(&Type::ByteArray, TypePosition::Param), "&[u8]");
        assert_eq!(
            render_type(&Type::ByteArray, TypePosition::Return),
            "Vec<u8>"
        );
        assert_eq!(
            render_type(
                &Type::Option(Box::new(Type::UInt(32))),
                TypePosition::Return
            ),
            "Option<u32>"
        );
        assert_eq!(
            render_type(
                &Type::Except(
                    Box::new(Type::Named("ParseError".into())),
                    Box::new(Type::UInt(8))
                ),
                TypePosition::Return
            ),
            "Result<u8, ParseError>"
        );
    }

    #[test]
    fn render_binop_table() {
        assert_eq!(render_binop(BinOp::Add), "+");
        assert_eq!(render_binop(BinOp::Shl), "<<");
        assert_eq!(render_binop(BinOp::Eq), "==");
        assert_eq!(render_binop(BinOp::NEq), "!=");
    }
}
