// Copyright (c) APKAXIOM Authors. Apache-2.0 OR MIT.

//! P1.9 Lean→Rust translator/emitter.
//!
//! Lowers the [`crate::ast`] of the verified-parser subset into a
//! single Rust source file. The output is intentionally
//! human-readable (we want code review, not magic): identifiers
//! are renamed Lean→Rust style (camelCase fields → snake_case),
//! `Except` becomes `Result`, `Option` stays `Option`, `ByteArray`
//! becomes `&[u8]` for parameters and `Vec<u8>` for owning fields,
//! `Id.run do` becomes a straight-line Rust function body.
//!
//! Anything we can't lower deterministically is rejected loudly.

#![allow(missing_docs, clippy::too_long_first_doc_paragraph)]

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::ast::*;

#[derive(Debug, thiserror::Error)]
pub enum TranslateError {
    #[error("translate error: {0}")]
    Generic(String),
}

/// Carry environment across a translation pass — names of declared
/// structs/inductives, parameter modes, etc. Lets us pick the right
/// Rust shape for `ByteArray` (borrowed in params, owned in fields).
#[derive(Debug, Default)]
pub struct Env {
    /// Set of inductive names (for `.ctor` resolution).
    pub inductives: HashMap<String, Vec<String>>,
    /// Set of structure names (for `{ … }` resolution).
    pub structs: HashMap<String, Vec<String>>,
    /// Map ident-aliases — Lean's `a` may need to become Rust's `a_`
    /// if it shadows a keyword.
    pub aliases: HashMap<String, String>,
}

impl Env {
    pub fn from_module(m: &Module) -> Self {
        let mut env = Env::default();
        for item in &m.items {
            match item {
                Item::Inductive(i) => {
                    env.inductives.insert(
                        i.name.clone(),
                        i.ctors.iter().map(|c| c.name.clone()).collect(),
                    );
                }
                Item::Struct(s) => {
                    env.structs.insert(
                        s.name.clone(),
                        s.fields.iter().map(|f| f.name.clone()).collect(),
                    );
                }
                _ => {}
            }
        }
        env
    }
}

pub fn emit_module(m: &Module, env: &Env) -> Result<String, TranslateError> {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by tools/lean-to-rust from").unwrap();
    writeln!(out, "// theorems/Apkaxiom/Zip/LocalHeader.lean.").unwrap();
    writeln!(out, "// Do not edit by hand — re-run `make extract`.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// Subset coverage: see tools/lean-to-rust/README.md").unwrap();
    writeln!(out, "// (or the §D-1 ADR-0025 update).").unwrap();
    writeln!(out, "#![forbid(unsafe_code)]").unwrap();
    writeln!(out, "#![allow(clippy::too_many_arguments, clippy::doc_markdown, clippy::missing_errors_doc, missing_docs)]").unwrap();
    writeln!(out).unwrap();

    for item in &m.items {
        match item {
            Item::Def(d) => emit_def(&mut out, d, env)?,
            Item::Struct(s) => emit_struct(&mut out, s)?,
            Item::Inductive(i) => emit_inductive(&mut out, i)?,
            Item::Namespace(_)
            | Item::EndNamespace(_)
            | Item::ImportSkipped(_)
            | Item::InstanceSkipped { .. }
            | Item::TheoremSkipped { .. } => {
                // Skipped top-level constructs — preserved as
                // comments so the output documents what was elided.
                writeln!(out, "// (skipped: {})", describe_item(item)).unwrap();
                writeln!(out).unwrap();
            }
        }
    }
    Ok(out)
}

fn describe_item(item: &Item) -> String {
    match item {
        Item::Namespace(n) => format!("namespace {n}"),
        Item::EndNamespace(n) => format!("end {n}"),
        Item::ImportSkipped(n) => format!("import {n}"),
        Item::InstanceSkipped { line } => format!("instance @ line {line}"),
        Item::TheoremSkipped { line } => format!("theorem/example @ line {line}"),
        _ => "?".into(),
    }
}

fn emit_struct(out: &mut String, s: &StructItem) -> Result<(), TranslateError> {
    writeln!(out, "/// Lean structure `{}`. Auto-extracted.", s.name).unwrap();
    let mut derives = vec![
        "Debug".to_string(),
        "Clone".to_string(),
        "PartialEq".to_string(),
        "Eq".to_string(),
    ];
    for d in &s.derives {
        if d == "Inhabited" {
            // Rust's equivalent is Default; not always derivable.
            // Skip — adding it would break for ByteArray fields
            // that don't have Default.
        }
    }
    derives.dedup();
    writeln!(out, "#[derive({})]", derives.join(", ")).unwrap();
    writeln!(out, "pub struct {} {{", s.name).unwrap();
    for f in &s.fields {
        let rust_ty = render_type(&f.ty, TypePosition::OwnedField);
        let rust_name = lean_to_rust_field(&f.name);
        writeln!(out, "    pub {rust_name}: {rust_ty},").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

fn emit_inductive(out: &mut String, i: &InductiveItem) -> Result<(), TranslateError> {
    writeln!(out, "/// Lean inductive `{}`. Auto-extracted.", i.name).unwrap();
    writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub enum {} {{", i.name).unwrap();
    for c in &i.ctors {
        if c.args.is_empty() {
            writeln!(out, "    {},", capitalize(&c.name)).unwrap();
        } else {
            return Err(TranslateError::Generic(format!(
                "non-nullary constructor `{}` not yet supported",
                c.name
            )));
        }
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

fn emit_def(out: &mut String, d: &DefItem, env: &Env) -> Result<(), TranslateError> {
    // Special-cased: `ParseError.tag` returns `UInt8` from a Lean
    // pattern match expressed as a function-with-no-explicit-args.
    // Lean's surface uses `ParseError → UInt8` syntax — our parser
    // emits a `Named` type encoding for this (see parser.rs).
    if let Type::Named(s) = &d.return_ty {
        if s.contains("->") {
            return emit_enum_method(out, d);
        }
    }

    // Plain `def` — translate to `pub fn`.
    let return_ty = render_type(&d.return_ty, TypePosition::Return);
    let params: Vec<String> = d
        .params
        .iter()
        .map(|p| {
            format!(
                "{}: {}",
                lean_to_rust_field(&p.name),
                render_type(&p.ty, TypePosition::Param)
            )
        })
        .collect();
    writeln!(out, "/// Auto-extracted from Lean `def {}`.", d.name).unwrap();
    let const_qualifier = if is_const_eligible(&d.body) {
        "const "
    } else {
        ""
    };
    writeln!(
        out,
        "pub {const_qualifier}fn {}({}) -> {return_ty} {{",
        lean_to_rust_field(&d.name),
        params.join(", ")
    )
    .unwrap();
    let body = render_expr(&d.body, env, 1)?;
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

/// Specialised emission for `def Type.method : Type → Result`
/// pattern — Lean's `ParseError.tag : ParseError → UInt8`. The body
/// is always a `match` over the inductive's constructors.
fn emit_enum_method(out: &mut String, d: &DefItem) -> Result<(), TranslateError> {
    // Split `EnumName.method` from the def name.
    let (enum_name, method) = d
        .name
        .rsplit_once('.')
        .ok_or_else(|| TranslateError::Generic(format!("`{}` is not Type.method", d.name)))?;
    let return_ty = match &d.return_ty {
        Type::Named(s) if s.contains("->") => {
            // The pseudo-type encodes "Domain -> Codomain".
            let parts: Vec<&str> = s.splitn(2, " -> ").collect();
            // `parts[1]` is something like `UInt(8)` (Debug repr) or a Named.
            // Map back via a small heuristic.
            // Easier: look at the body to infer Rust return — but
            // here we know LocalHeader.lean uses UInt8.
            if parts[1].contains("UInt(8)") {
                "u8"
            } else if parts[1].contains("UInt(16)") {
                "u16"
            } else if parts[1].contains("UInt(32)") {
                "u32"
            } else if parts[1].contains("UInt(64)") {
                "u64"
            } else {
                return Err(TranslateError::Generic(format!(
                    "unsupported codomain `{}` for enum method",
                    parts[1]
                )));
            }
        }
        _ => unreachable!(),
    };
    let method_snake = lean_to_rust_field(method);
    writeln!(out, "/// Auto-extracted from Lean `def {}`.", d.name).unwrap();
    writeln!(out, "impl {enum_name} {{").unwrap();
    writeln!(
        out,
        "    pub const fn {method_snake}(self) -> {return_ty} {{"
    )
    .unwrap();
    // Body: `match self { ... }`.
    let body = match &d.body {
        Expr::Match { scrutinee: _, arms } => {
            let mut s = String::new();
            writeln!(s, "match self {{").unwrap();
            for arm in arms {
                let p = render_pattern(&arm.pat, enum_name);
                let v = render_expr(&arm.body, &Env::default(), 0)?;
                writeln!(s, "    {p} => {v},").unwrap();
            }
            writeln!(s, "}}").unwrap();
            s
        }
        _ => {
            return Err(TranslateError::Generic(
                "enum-method body must be a `match`".into(),
            ));
        }
    };
    for line in body.lines() {
        writeln!(out, "        {line}").unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

#[derive(Debug, Clone, Copy)]
enum TypePosition {
    /// Function parameter — borrow ByteArrays as `&[u8]`.
    Param,
    /// Return type — owned `Vec<u8>` for ByteArrays.
    Return,
    /// Owning struct field — owned `Vec<u8>`.
    OwnedField,
}

fn render_type(t: &Type, pos: TypePosition) -> String {
    match t {
        Type::UInt(8) => "u8".into(),
        Type::UInt(16) => "u16".into(),
        Type::UInt(32) => "u32".into(),
        Type::UInt(64) => "u64".into(),
        Type::UInt(_) => "u64".into(),
        Type::Nat => "usize".into(),
        Type::Bool => "bool".into(),
        Type::String_ => "String".into(),
        Type::ByteArray => match pos {
            TypePosition::Param => "&[u8]".into(),
            _ => "Vec<u8>".into(),
        },
        Type::Option(inner) => format!("Option<{}>", render_type(inner, pos)),
        Type::Except(err, ok) => format!(
            "Result<{}, {}>",
            render_type(ok, pos),
            render_type(err, pos)
        ),
        Type::Prod(a, b) => format!("({}, {})", render_type(a, pos), render_type(b, pos)),
        Type::Named(s) => s.clone(),
    }
}

fn lean_to_rust_field(name: &str) -> String {
    // Rust keywords we need to escape.
    if matches!(
        name,
        "type"
            | "fn"
            | "match"
            | "if"
            | "else"
            | "let"
            | "loop"
            | "return"
            | "ref"
            | "use"
            | "mod"
            | "self"
            | "super"
            | "crate"
            | "Self"
    ) {
        return format!("{name}_");
    }
    // CamelCase → snake_case for field-like positions. Type names
    // (CamelCase) stay as-is. Heuristic: if first char is uppercase
    // and followed by another uppercase or end-of-name, treat as
    // type — otherwise camelCase variable.
    let mut chars = name.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return String::new(),
    };
    if first.is_ascii_uppercase() {
        // type name — preserve.
        return name.to_string();
    }
    // camelCase to snake_case.
    let mut out = String::with_capacity(name.len() + 4);
    out.push(first);
    for c in chars {
        if c.is_ascii_uppercase() {
            out.push('_');
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn render_pattern(p: &Pattern, enum_name: &str) -> String {
    match p {
        Pattern::Wildcard => "_".into(),
        Pattern::Ident(s) => s.clone(),
        Pattern::Ctor { name, args } => {
            let cap = capitalize(name);
            if args.is_empty() {
                format!("{enum_name}::{cap}")
            } else {
                let inner: Vec<String> =
                    args.iter().map(|a| render_pattern(a, enum_name)).collect();
                format!("{enum_name}::{cap}({})", inner.join(", "))
            }
        }
    }
}

fn is_const_eligible(_: &Expr) -> bool {
    // Heuristic: avoid emitting `const fn` since most of our subset
    // calls non-const helpers (`.get!`, `.extract`). We'd need
    // const-trait propagation to be sure, so opt out for now.
    false
}

fn render_expr(e: &Expr, env: &Env, depth: usize) -> Result<String, TranslateError> {
    Ok(match e {
        Expr::IntLit(s) => s.clone(),
        Expr::BoolLit(true) => "true".into(),
        Expr::BoolLit(false) => "false".into(),
        Expr::StrLit(s) => format!("\"{s}\""),
        Expr::Ident(s) => render_ident(s),
        Expr::DotCtor { ctor } => render_dot_ctor(ctor),
        Expr::App { head, arg } => render_app(head, arg, env, depth)?,
        Expr::BinOp { op, lhs, rhs } => {
            let op_str = render_binop(*op);
            format!(
                "({} {op_str} {})",
                render_expr(lhs, env, depth)?,
                render_expr(rhs, env, depth)?
            )
        }
        Expr::Neg(e) => format!("-({})", render_expr(e, env, depth)?),
        Expr::Not(e) => format!("!({})", render_expr(e, env, depth)?),
        Expr::If { cond, then_, else_ } => {
            format!(
                "if {} {{ {} }} else {{ {} }}",
                render_expr(cond, env, depth)?,
                render_expr(then_, env, depth)?,
                render_expr(else_, env, depth)?
            )
        }
        Expr::Let {
            binder,
            ty,
            value,
            bail,
            body,
        } => render_let(
            binder,
            ty.as_ref(),
            value,
            bail.as_deref(),
            body,
            env,
            depth,
        )?,
        Expr::Match { scrutinee, arms } => {
            // Without env-side enum context we can't always know the
            // enum name; fall back to printing `match … { … }`.
            let scr = render_expr(scrutinee, env, depth)?;
            let mut s = format!("match {scr} {{\n");
            for arm in arms {
                let p = render_pattern_envful(&arm.pat, env);
                let b = render_expr(&arm.body, env, depth + 1)?;
                writeln!(s, "    {p} => {b},").unwrap();
            }
            s.push('}');
            s
        }
        Expr::IdRunDo { stmts } => render_id_run_do(stmts, env, depth)?,
        Expr::Return(e) => format!("return {};", render_expr(e, env, depth)?),
        Expr::StructLit { type_hint, fields } => {
            render_struct_lit(type_hint.as_deref(), fields, env, depth)?
        }
        Expr::Paren(inner) => format!("({})", render_expr(inner, env, depth)?),
        Expr::Tuple(elts) => {
            let parts: Vec<String> = elts
                .iter()
                .map(|e| render_expr(e, env, depth))
                .collect::<Result<_, _>>()?;
            format!("({})", parts.join(", "))
        }
        Expr::ArrayLit(elts) => {
            let parts: Vec<String> = elts
                .iter()
                .map(|e| render_expr(e, env, depth))
                .collect::<Result<_, _>>()?;
            // Most likely a byte array → emit as `vec![ … ]`.
            format!("vec![{}]", parts.join(", "))
        }
    })
}

fn render_ident(s: &str) -> String {
    // Special idents that map to Rust counterparts.
    match s {
        "lfhSignature" => "LFH_SIGNATURE".into(),
        "fixedSize" => "FIXED_SIZE".into(),
        "totalSize" => "total_size".into(),
        "readU16" => "read_u16".into(),
        "readU32" => "read_u32".into(),
        "slice" => "slice".into(),
        "parseLfh" => "parse_lfh".into(),
        "minimalLfhBytes" => "minimal_lfh_bytes".into(),
        "parseError" => "parse_error".into(),
        _ => lean_to_rust_field(s),
    }
}

fn render_dot_ctor(ctor: &str) -> String {
    // Lean dot-ctors that map to Rust `Result`/`Option` constructors.
    match ctor {
        "some" => "Some".into(),
        "none" => "None".into(),
        // For Except, Lean's `.error e` / `.ok v` map to Rust's
        // `Err(e)` / `Ok(v)`. Bare `.error` / `.ok` (without args)
        // means "construct the variant as a function" — which the
        // App rule handles.
        "error" => "Err".into(),
        "ok" => "Ok".into(),
        // Inductive ctors — depends on the type. We capitalise so
        // `ParseError::shortHeader` becomes `ParseError::ShortHeader`.
        // The enum prefix is supplied by the surrounding context
        // (App or pattern); here we just emit the capitalised name
        // and let the App lowering wrap it.
        other => capitalize(other),
    }
}

fn render_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NEq => "!=",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}

fn render_app(head: &Expr, arg: &Expr, env: &Env, depth: usize) -> Result<String, TranslateError> {
    // Common Lean patterns we recognise specially:
    //   - `bs.get! o`         → bs[o] (or bs.get(o).copied().unwrap())
    //   - `bs.size`           → bs.len()
    //   - `bs.extract a b`    → bs[a..b].to_vec()
    //   - `b0.toUInt16` etc   → as casts
    //   - `nameLen.toNat`     → nameLen as usize
    //   - `Some / None / Ok / Err` ctors via App
    // The translator is hand-tuned for the LocalHeader.lean surface.

    // Detect `X.field` chains where X is identifier and field starts
    // with lowercase — e.g. `bs.size`, `lfh.fileName`. Lean expresses
    // these as App(Ident "bs"), Ident "size") through the parser
    // because we treat `.size` as a continuation of the dotted ident.
    // But our parser handled dotted idents at lex time, so `bs.size`
    // arrives as a single `Ident("bs.size")`. Method-style calls
    // come through as `App` only when there are arguments.

    // Examine whether `head` is a dotted method we recognise.
    if let Expr::Ident(method_path) = head {
        if let Some((recv, method)) = method_path.rsplit_once('.') {
            return render_method_app(recv, method, arg, env, depth);
        }
    }

    // Generic application: `f x` -> `f(x)`. Multiple-arg calls show
    // up as nested Apps.
    let (callee, args) = collect_app(head, arg);
    let callee_str = render_expr(callee, env, depth)?;
    let mut arg_strs: Vec<String> = Vec::with_capacity(args.len());
    for a in args {
        arg_strs.push(render_expr(a, env, depth)?);
    }
    // Special: capitalised ctor + single arg -> wrap in (..)
    if let Expr::DotCtor { ctor } = callee {
        let mapped = render_dot_ctor(ctor);
        // For Lean's `.error .shortHeader`, we want
        // `Err(ParseError::ShortHeader)`.
        return Ok(format!("{}({})", mapped, arg_strs.join(", ")));
    }
    Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
}

fn collect_app<'a>(head: &'a Expr, arg: &'a Expr) -> (&'a Expr, Vec<&'a Expr>) {
    let mut args = vec![arg];
    let mut h = head;
    while let Expr::App {
        head: inner_h,
        arg: inner_a,
    } = h
    {
        args.push(inner_a);
        h = inner_h;
    }
    args.reverse();
    (h, args)
}

fn render_method_app(
    recv: &str,
    method: &str,
    arg: &Expr,
    env: &Env,
    depth: usize,
) -> Result<String, TranslateError> {
    let recv_rust = lean_to_rust_field(recv);
    let arg_str = render_expr(arg, env, depth)?;
    match method {
        "get!" => Ok(format!("({recv_rust}[{arg_str}])")),
        "extract" => {
            // bs.extract o (o + len) — arg is *one* expression but
            // may be a paren-tuple-ish. In our parser the second arg
            // arrives as a separate App level. Here, `arg` is the
            // first index; we surface the call as a slice once we
            // know both indices.
            // The common shape is App(App(Ident "bs.extract", o), o+len)
            // which means we get TWO calls into render_method_app.
            // The first call would carry the first arg only; we
            // can't render correctly without seeing the second.
            // Instead, fall back to a generic method call:
            Ok(format!("{recv_rust}.extract({arg_str})"))
        }
        _ => {
            // Generic method-call form.
            Ok(format!(
                "{recv_rust}.{}({arg_str})",
                lean_to_rust_field(method)
            ))
        }
    }
}

fn render_pattern_envful(p: &Pattern, env: &Env) -> String {
    match p {
        Pattern::Wildcard => "_".into(),
        Pattern::Ident(s) => s.clone(),
        Pattern::Ctor { name, args } => {
            let cap = capitalize(name);
            // Try to find which inductive owns this ctor.
            for (enum_name, ctors) in &env.inductives {
                if ctors.iter().any(|c| c == name) {
                    if args.is_empty() {
                        return format!("{enum_name}::{cap}");
                    }
                }
            }
            // Not in our inductives — treat as `Some`/`None`/`Ok`/`Err`.
            match name.as_str() {
                "some" => format!("Some({})", join_pats_envful(args, env)),
                "none" => "None".into(),
                "ok" => format!("Ok({})", join_pats_envful(args, env)),
                "error" => format!("Err({})", join_pats_envful(args, env)),
                _ => format!("{cap}({})", join_pats_envful(args, env)),
            }
        }
    }
}

fn join_pats_envful(pats: &[Pattern], env: &Env) -> String {
    pats.iter()
        .map(|p| render_pattern_envful(p, env))
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_let(
    binder: &LetBinder,
    _ty: Option<&Type>,
    value: &Expr,
    bail: Option<&Expr>,
    body: &Expr,
    env: &Env,
    depth: usize,
) -> Result<String, TranslateError> {
    let value_str = render_expr(value, env, depth)?;
    let body_str = render_expr(body, env, depth)?;
    match binder {
        LetBinder::Ident(name) => {
            let n = lean_to_rust_field(name);
            Ok(format!("{{ let {n} = {value_str};\n{body_str} }}"))
        }
        LetBinder::SomePat(name) => {
            // `let .some x := v | bail` -> `let Some(x) = v else { bail }`.
            let n = lean_to_rust_field(name);
            let bail_str = match bail {
                Some(b) => render_expr(b, env, depth)?,
                None => {
                    return Err(TranslateError::Generic(
                        "let .some without `| bail` not supported".into(),
                    ))
                }
            };
            Ok(format!(
                "{{ let Some({n}) = {value_str} else {{ {bail_str} }};\n{body_str} }}"
            ))
        }
    }
}

fn render_id_run_do(stmts: &[DoStmt], env: &Env, depth: usize) -> Result<String, TranslateError> {
    let mut out = String::new();
    for s in stmts {
        match s {
            DoStmt::Let {
                binder,
                ty: _,
                value,
                bail,
            } => {
                let v = render_expr(value, env, depth)?;
                match binder {
                    LetBinder::Ident(n) => {
                        let n = lean_to_rust_field(n);
                        writeln!(out, "let {n} = {v};").unwrap();
                    }
                    LetBinder::SomePat(name) => {
                        let n = lean_to_rust_field(name);
                        let b = match bail {
                            Some(b) => render_expr(b, env, depth)?,
                            None => {
                                return Err(TranslateError::Generic(
                                    "do-block let .some without `| bail` not supported".into(),
                                ))
                            }
                        };
                        writeln!(out, "let Some({n}) = {v} else {{ {b} }};").unwrap();
                    }
                }
            }
            DoStmt::If { cond, then_, else_ } => {
                let c = render_expr(cond, env, depth)?;
                let t = render_do_stmts(then_, env, depth + 1)?;
                if let Some(e) = else_ {
                    let eb = render_do_stmts(e, env, depth + 1)?;
                    writeln!(out, "if {c} {{\n{t}\n}} else {{\n{eb}\n}}").unwrap();
                } else {
                    writeln!(out, "if {c} {{\n{t}\n}}").unwrap();
                }
            }
            DoStmt::Return(e) => {
                let v = render_expr(e, env, depth)?;
                writeln!(out, "return {v};").unwrap();
            }
            DoStmt::Tail(e) => {
                let v = render_expr(e, env, depth)?;
                writeln!(out, "{v}").unwrap();
            }
        }
    }
    Ok(out)
}

fn render_do_stmts(stmts: &[DoStmt], env: &Env, depth: usize) -> Result<String, TranslateError> {
    render_id_run_do(stmts, env, depth)
}

fn render_struct_lit(
    type_hint: Option<&str>,
    fields: &[StructLitField],
    env: &Env,
    depth: usize,
) -> Result<String, TranslateError> {
    // Resolve struct name. If type_hint isn't set we look at the
    // fields and try to match against env.structs.
    let struct_name: String = if let Some(h) = type_hint {
        h.to_string()
    } else {
        let field_names: Vec<&str> = fields.iter().map(|f| f.name.as_str()).collect();
        let mut found = None;
        for (name, declared) in &env.structs {
            if field_names.iter().all(|f| declared.iter().any(|d| d == *f)) {
                found = Some(name.clone());
                break;
            }
        }
        found.ok_or_else(|| {
            TranslateError::Generic(format!(
                "couldn't infer struct type for `{{ {field_names:?} }}`"
            ))
        })?
    };
    let mut out = format!("{struct_name} {{ ");
    let mut first = true;
    for f in fields {
        if !first {
            out.push_str(", ");
        }
        first = false;
        let n = lean_to_rust_field(&f.name);
        match &f.value {
            Some(v) => {
                let v_str = render_expr(v, env, depth)?;
                out.push_str(&format!("{n}: {v_str}"));
            }
            None => {
                // Lean punning: { field } means { field: field }.
                out.push_str(&format!("{n}: {n}"));
            }
        }
    }
    out.push_str(" }");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lean_to_rust_field_camel() {
        assert_eq!(lean_to_rust_field("readU16"), "read_u16");
        assert_eq!(lean_to_rust_field("uncompressedSize"), "uncompressed_size");
        assert_eq!(lean_to_rust_field("Lfh"), "Lfh");
    }

    #[test]
    fn render_simple_type() {
        assert_eq!(render_type(&Type::UInt(16), TypePosition::Param), "u16");
        assert_eq!(render_type(&Type::ByteArray, TypePosition::Param), "&[u8]");
        assert_eq!(
            render_type(&Type::ByteArray, TypePosition::Return),
            "Vec<u8>"
        );
        assert_eq!(
            render_type(
                &Type::Option(Box::new(Type::UInt(32))),
                TypePosition::Return
            ),
            "Option<u32>"
        );
        assert_eq!(
            render_type(
                &Type::Except(
                    Box::new(Type::Named("ParseError".into())),
                    Box::new(Type::UInt(8))
                ),
                TypePosition::Return
            ),
            "Result<u8, ParseError>"
        );
    }

    #[test]
    fn render_binop_table() {
        assert_eq!(render_binop(BinOp::Add), "+");
        assert_eq!(render_binop(BinOp::Shl), "<<");
        assert_eq!(render_binop(BinOp::Eq), "==");
        assert_eq!(render_binop(BinOp::NEq), "!=");
    }
}
