#!/usr/bin/env bash
# Copyright (c) APKAXIOM Authors. Apache-2.0 OR MIT.
#
# hash-snapshot.sh — write a per-platform hash snapshot to
# `docs/reproducibility-hashes.<os>-<arch>.txt`.
#
# Invariants (per-platform, not cross-platform):
#  - Same git SHA + same flake.lock + same platform → identical snapshot.
#  - Cross-platform diffs are *expected* (rlibs are arch-specific). The CI
#    `verify-hashes` job diffs only same-platform across runners.
#
# To bake a new reference: run inside `nix develop` on a clean checkout, then
# commit the resulting `docs/reproducibility-hashes.<platform>.txt`. Bumps
# go through ADR-0004 review.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

UNAME_S=$(uname -s | tr '[:upper:]' '[:lower:]')
UNAME_M=$(uname -m)
PLATFORM="$UNAME_S-$UNAME_M"
OUT="docs/reproducibility-hashes.$PLATFORM.txt"

mkdir -p docs

buck2 clean
HASHES="$(bash scripts/_hash-artifacts.sh)"

{
  echo "# APKAXIOM reproducibility-hashes — $PLATFORM"
  echo "# Generated by scripts/hash-snapshot.sh"
  echo "# git SHA:  $(git rev-parse HEAD 2>/dev/null || echo '<no commit yet>')"
  echo "# rustc:    $(rustc --version)"
  echo "# buck2:    $(buck2 --version | head -1)"
  echo "# UTC date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "#"
  echo "# Format: <sha256>  <artifact-basename>"
  echo "# These hashes are *per-platform*. rlibs/rmeta are arch-specific by"
  echo "# definition, so cross-platform diffs are expected and ignored by CI."
  echo
  echo "$HASHES"
} > "$OUT"

echo "Wrote: $OUT" >&2
echo >&2
cat "$OUT" >&2
