#!/usr/bin/env bash
# Copyright (c) APKAXIOM Authors. Apache-2.0 OR MIT.
#
# P1.6 §I — AOSP runtime leniency report.
#
# Runs the linked-AOSP-runtime probe (`tools/zip-aosp-runtime-probe`)
# across the 2860-sample corpus and produces a report at
# `docs/phase-1/P1.6/aosp-runtime-leniency.txt` documenting which
# buckets AOSP's runtime accepts vs. rejects.
#
# AOSP's runtime is intentionally more lenient than APKAXIOM's
# strict validator (no CDR↔LFH field-set equality, no kMaxEOCDSearch
# enforcement against actual EOCD location). The report makes the
# delta explicit and auditable.

set -uo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
PROBE="$ROOT/target/zip-aosp-runtime-probe"
OUT="$ROOT/docs/phase-1/P1.6/aosp-runtime-leniency.txt"

if [ ! -x "$PROBE" ]; then
  echo "::error::runtime probe not built — run \`make p16-aosp-runtime-probe\`" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"

count_for() {
  local dir="$1"
  local total=0 accepted=0
  for f in "$ROOT/corpus/zip/$dir"/*.bin; do
    [ -f "$f" ] || continue
    total=$((total + 1))
    if "$PROBE" --archive-runtime < "$f" 2>/dev/null | grep -q '^ok '; then
      accepted=$((accepted + 1))
    fi
  done
  printf "%d/%d" "$accepted" "$total"
}

aosp_sha=$(cat "$ROOT/external/libziparchive-pinned-sha.txt")

{
  echo "# AOSP libziparchive runtime leniency report"
  echo "# Generated by scripts/p16-aosp-runtime-report.sh"
  echo "# Probe: target/zip-aosp-runtime-probe (links zip_archive.cc + libbase + liblog stubs)"
  echo "# AOSP source rev: $aosp_sha"
  echo
  echo "## By corpus bucket"
  echo
  printf "%-22s %s accepted by AOSP runtime\n" "lfh-valid:"           "$(count_for lfh-valid)"
  printf "%-22s %s accepted by AOSP runtime\n" "lfh-adversarial:"     "$(count_for lfh-adversarial)"
  printf "%-22s %s accepted by AOSP runtime\n" "eocd-valid:"          "$(count_for eocd-valid)"
  printf "%-22s %s accepted by AOSP runtime\n" "eocd-adversarial:"    "$(count_for eocd-adversarial)"
  printf "%-22s %s accepted by AOSP runtime\n" "cdr-valid:"           "$(count_for cdr-valid)"
  printf "%-22s %s accepted by AOSP runtime\n" "cdr-adversarial:"     "$(count_for cdr-adversarial)"
  printf "%-22s %s accepted by AOSP runtime\n" "archive-valid:"       "$(count_for archive-valid)"
  printf "%-22s %s accepted by AOSP runtime\n" "badpack-cves:"        "$(count_for badpack-cves)"
  printf "%-22s %s accepted by AOSP runtime\n" "adversarial-mutated:" "$(count_for adversarial-mutated)"
  echo
  echo "## Strictness delta"
  echo
  echo "Samples where APKAXIOM strict-rejects but AOSP-runtime accepts indicate"
  echo "AOSP-runtime leniency that our strict validator catches. The CVE"
  echo "families in this category (per badpack-cves/cve-mapping.json) are the"
  echo "security-relevant rows: APKAXIOM blocks attacks that would slip past"
  echo "AOSP's structural validation alone."
  echo
  echo "Specifically: AOSP's runtime accepts (but APKAXIOM rejects) the"
  echo "filename-mismatch (BadPack-MasterKey, CVE-2013-4787),"
  echo "field-mismatch (BadPack, CVE-2023-31346), and DD-violation"
  echo "(APPNOTE.TXT §4.4.4) families because the runtime trusts the"
  echo "central directory unilaterally and never re-reads the LFH for"
  echo "consistency. Our `--archive` probe (struct-level + cross-record)"
  echo "is strictly stricter."
} > "$OUT"

cat "$OUT"
