#!/usr/bin/env bash
# Copyright (c) APKAXIOM Authors. Apache-2.0 OR MIT.
#
# wall-time-rollup.sh — query the GitHub Actions API for the recent
# CI runs of the `CI` workflow, compute p50/p95/p99/max wall-times per
# job, and append a rolling NDJSON record + regenerate the Markdown
# rollup. Per K10 (PHASE_GATES.md §5).
#
# The script emits two artefacts:
#
#   docs/phase-1/P1.1/wall-time.ndjson          — append-only NDJSON, one
#                                                 line per (workflow run,
#                                                 job) measurement. The
#                                                 source of truth.
#
#   docs/phase-1/P1.1/wall-time-rollup.md       — regenerated rollup of the
#                                                 last 200 runs: percentile
#                                                 table per (job, platform).
#
# Run modes:
#   - Local:    `nix run .#wall-time-rollup` — needs `gh auth login`.
#   - CI cron:  the wall-time-rollup workflow runs this nightly and
#               commits the regenerated files.
#
# Invariants:
#   - We never *delete* historical samples; only append. p99 over a long
#     window is the meaningful metric, not a moving rewriting of history.
#   - The script is idempotent w.r.t. duplicate (run_id, job_id) pairs.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

NDJSON="docs/phase-1/P1.1/wall-time.ndjson"
ROLLUP="docs/phase-1/P1.1/wall-time-rollup.md"
WINDOW=200

mkdir -p "$(dirname "$NDJSON")"
touch "$NDJSON"

# Pull recent CI runs. `gh run list` is paginated; we cap at 100 most
# recent, run twice if more are needed (`--limit 200`).
echo "=== fetching last 200 CI runs from GitHub Actions ==="
runs_json=$(gh run list \
  --workflow=CI \
  --limit 200 \
  --json databaseId,conclusion,createdAt,updatedAt,event,headBranch,headSha \
  2>/dev/null || true)
if [[ -z "$runs_json" ]]; then
  echo "No CI runs found yet (this is normal pre-first-run). Exiting." >&2
  exit 0
fi

# For each run, pull job-level timings. Idempotence relies on grep below
# rather than a precomputed set — the NDJSON is small.

new_records=0
while IFS= read -r run_id; do
  jobs_json=$(gh api "repos/{owner}/{repo}/actions/runs/${run_id}/jobs" \
    --jq '.jobs[] | {id, name, status, conclusion, started_at, completed_at}' 2>/dev/null || true)
  [[ -z "$jobs_json" ]] && continue
  while IFS= read -r job; do
    [[ -z "$job" ]] && continue
    job_id=$(jq -r '.id' <<<"$job")
    name=$(jq -r '.name' <<<"$job")
    status=$(jq -r '.status' <<<"$job")
    conclusion=$(jq -r '.conclusion' <<<"$job")
    started=$(jq -r '.started_at // empty' <<<"$job")
    completed=$(jq -r '.completed_at // empty' <<<"$job")
    [[ -z "$started" || -z "$completed" || "$status" != "completed" ]] && continue
    # Skip if we've already recorded this (run_id, job_id).
    if grep -qF "${run_id}|${job_id}|" "$NDJSON" 2>/dev/null; then
      continue
    fi
    # Compute wall-time in seconds.
    s_epoch=$(date -u -d "$started" +%s)
    e_epoch=$(date -u -d "$completed" +%s)
    seconds=$((e_epoch - s_epoch))
    record=$(jq -n \
      --arg run_id "$run_id" --arg job_id "$job_id" --arg name "$name" \
      --arg conclusion "$conclusion" --arg started "$started" \
      --arg completed "$completed" --argjson seconds "$seconds" \
      '{run_id:$run_id, job_id:$job_id, name:$name, conclusion:$conclusion,
        started:$started, completed:$completed, seconds:$seconds}')
    # NDJSON line: leading "<run_id>|<job_id>|" makes idempotence cheap with grep.
    echo "${run_id}|${job_id}|${record}" >> "$NDJSON"
    new_records=$((new_records + 1))
  done <<< "$(echo "$jobs_json" | jq -c '.')"
done <<< "$(echo "$runs_json" | jq -r '.[].databaseId')"

echo "Appended $new_records new records to $NDJSON ($(wc -l <"$NDJSON") total)."

# Rebuild the rollup. The rollup considers the last $WINDOW records per
# (job-name) and reports the percentile distribution.
{
  echo "# CI wall-time rollup — last $WINDOW records per job"
  echo
  echo "> Generated by \`scripts/wall-time-rollup.sh\`. Source data:"
  echo "> [\`wall-time.ndjson\`](./wall-time.ndjson). Updated nightly."
  echo
  echo "**Hard gate (K10):** every job's p99 must be ≤ 25 min (1500 s)."
  echo
  echo "| job | n | p50 (s) | p95 (s) | p99 (s) | max (s) | gate |"
  echo "|-----|---|---------|---------|---------|---------|------|"
  awk -F'|' '{print $3}' "$NDJSON" \
    | jq -r '"\(.name)\t\(.seconds)\t\(.conclusion)"' \
    | sort -k1,1 \
    | awk -F'\t' -v window="$WINDOW" '
        {
          name=$1; sec=$2;
          if (count[name]<window) {
            count[name]++;
            samples[name "@" count[name]]=sec;
          }
        }
        END {
          for (n in count) {
            cnt=count[n];
            for (i=1;i<=cnt;i++) arr[i]=samples[n "@" i]+0;
            # Sort numerically.
            for (i=1;i<=cnt;i++) for (j=i+1;j<=cnt;j++) if (arr[i]>arr[j]) {t=arr[i]; arr[i]=arr[j]; arr[j]=t}
            p50=arr[int(cnt*0.50)+1]; p95=arr[int(cnt*0.95)+1]; p99=arr[int(cnt*0.99)+1]; mx=arr[cnt];
            gate=(p99<=1500?"OK":"BREACH");
            printf "| %s | %d | %d | %d | %d | %d | %s |\n", n, cnt, p50, p95, p99, mx, gate;
            for (i=1;i<=cnt;i++) delete arr[i];
          }
        }
      ' | sort
} > "$ROLLUP"

echo "Wrote: $ROLLUP"
